import mutations from "./mutations.js";
import actions from "./actions.js";
import getters from "./getters.js";

export default {
    namespaced: true,
    state(){
        return {
            warehouse: {
                id: 1,
                farm_id: 1,
                products: [
                    {
                        id: 3,
                        name: "4Insect Abac 18 EC",
                        permit_number: "R-106/2020 h.r.",
                        permit_deadline: "2022-04-30",
                        sale_deadline: "2022-10-30",
                        term_for_use: "2023-10-30",
                        type: "Akarycyd, Insektycyd",
                        active_substance: "abamektyna - 18 g",
                        plant: null,
                        pest: "miodówka gruszowa plamista",
                        dose: "Maksymalna /zalecana dawka dla jednorazowego zastosowania: 0,75 l/ha.",
                        recommended_dose: null,
                        maximum_dose: 0.75,
                        unit: "l/ha",
                        deadline: null,
                        group_name: "ROŚLINY SADOWNICZE",
                        small_area: null,
                        application: "profesjonalne",
                        created_at: "2022-09-01T19:03:40.000000Z",
                        updated_at: "2022-09-01T19:03:40.000000Z",
                        pivot: {
                            magazine_id: 1,
                            plant_protection_product_id: 3,
                            quantity: 6,
                            created_at: "2022-09-02T11:45:20.000000Z",
                            updated_at: "2022-09-02T11:45:20.000000Z"
                        }
                    },
                    {
                        id: 8,
                        name: "Abamax 018 EC",
                        permit_number: "R-78/2018",
                        permit_deadline: "2022-04-30",
                        sale_deadline: "2022-10-30",
                        term_for_use: "2022-10-30",
                        type: "Akarycyd, Insektycyd",
                        active_substance: "abamektyna - 18 g",
                        plant: null,
                        pest: "przędziorek chmielowiec",
                        dose: "Maksymalna / zalecana dawka dla jednorazowego zastosowania: 1,2 l/ha.",
                        recommended_dose: null,
                        maximum_dose: 44593,
                        unit: "l/ha",
                        deadline: null,
                        group_name: "ROŚLINY SADOWNICZE",
                        small_area: "TAK",
                        application: "profesjonalne",
                        created_at: "2022-09-01T19:03:40.000000Z",
                        updated_at: "2022-09-01T19:03:40.000000Z",
                        pivot: {
                            magazine_id: 1,
                            plant_protection_product_id: 8,
                            quantity: 12,
                            created_at: "2022-09-02T11:45:30.000000Z",
                            updated_at: "2022-09-02T11:45:30.000000Z"
                        }
                    }
                ],
                created_at: "2022-09-01T13:32:11.000000Z",
                updated_at: "2022-09-01T13:32:11.000000Z"
            },
            allPlantProtectionProducts: [
                {
                    id: 1,
                    name: "1,4 Bulwa",
                    permit_number: "R-85/2021 h.r.",
                    permit_deadline: "2025-06-30",
                    sale_deadline: "2025-12-31",
                    term_for_use: "2026-12-31",
                    type: "Regulator wzrostu",
                    active_substance: "1,4-dimetylonaftalen - 980 g",
                    plant: null,
                    pest: "zapobieganie kiełkowania bulw",
                    dose: "Maksymalna/zalecana dawka dla jednorazowego zastosowania: 20 ml/1000 kg bulw",
                    recommended_dose: null,
                    maximum_dose: null,
                    unit: null,
                    deadline: "Środek zastosować po zbiorze (BBCH 99) i umieszczeniu partii bulw w przechowalni, następnie jeśli przewiduje się dłuższy okres przechowywania wykonać kolejne zabiegi   w odstępie co 4-6 tygodni",
                    group_name: "ROŚLINY ROLNICZE",
                    small_area: null,
                    application: "profesjonalne",
                    created_at: "2022-09-01T19:03:40.000000Z",
                    updated_at: "2022-09-01T19:03:40.000000Z"
                },
                {
                    id: 2,
                    name: "1,4Sight",
                    permit_number: "R-50/2018 wu",
                    permit_deadline: "2025-06-30",
                    sale_deadline: "2025-12-31",
                    term_for_use: "2026-12-31",
                    type: "Regulator wzrostu",
                    active_substance: "1,4-dimetylonaftalen - 980 g",
                    plant: null,
                    pest: "zapobieganie kiełkowania bulw",
                    dose: "Maksymalna/zalecana dawka dla jednorazowego zastosowania: 20 ml/1000 kg bulw",
                    recommended_dose: null,
                    maximum_dose: null,
                    unit: null,
                    deadline: "Środek zastosować po zbiorze (BBCH 99) i umieszczeniu partii bulw w przechowalni, następnie jeśli przewiduje się dłuższy okres przechowywania wykonać kolejne zabiegi   w odstępie co 4-6 tygodni.",
                    group_name: "ROŚLINY ROLNICZE",
                    small_area: null,
                    application: "profesjonalne",
                    created_at: "2022-09-01T19:03:40.000000Z",
                    updated_at: "2022-09-01T19:03:40.000000Z"
                },
                {
                    id: 3,
                    name: "4Insect Abac 18 EC",
                    permit_number: "R-106/2020 h.r.",
                    permit_deadline: "2022-04-30",
                    sale_deadline: "2022-10-30",
                    term_for_use: "2023-10-30",
                    type: "Akarycyd, Insektycyd",
                    active_substance: "abamektyna - 18 g",
                    plant: null,
                    pest: "miodówka gruszowa plamista",
                    dose: "Maksymalna /zalecana dawka dla jednorazowego zastosowania: 0,75 l/ha.",
                    recommended_dose: null,
                    maximum_dose: 0.75,
                    unit: "l/ha",
                    deadline: null,
                    group_name: "ROŚLINY SADOWNICZE",
                    small_area: null,
                    application: "profesjonalne",
                    created_at: "2022-09-01T19:03:40.000000Z",
                    updated_at: "2022-09-01T19:03:40.000000Z"
                },
                {
                    id: 4,
                    name: "4Insect Abac 18 EC",
                    permit_number: "R-106/2020 h.r.",
                    permit_deadline: "2022-04-30",
                    sale_deadline: "2022-10-30",
                    term_for_use: "2023-10-30",
                    type: "Akarycyd, Insektycyd",
                    active_substance: "abamektyna - 18 g",
                    plant: null,
                    pest: "przędziorek chmielowiec",
                    dose: "Maksymalna / zalecana dawka dla jednorazowego zastosowania: 0,05% (50 ml środka w 100 litrach wody).",
                    recommended_dose: null,
                    maximum_dose: null,
                    unit: null,
                    deadline: null,
                    group_name: "ROŚLINY WARZYWNE",
                    small_area: null,
                    application: "profesjonalne",
                    created_at: "2022-09-01T19:03:40.000000Z",
                    updated_at: "2022-09-01T19:03:40.000000Z"
                },
                {
                    id: 5,
                    name: "4Insect Abac 18 EC",
                    permit_number: "R-106/2020 h.r.",
                    permit_deadline: "2022-04-30",
                    sale_deadline: "2022-10-30",
                    term_for_use: "2023-10-30",
                    type: "Akarycyd, Insektycyd",
                    active_substance: "abamektyna - 18 g",
                    plant: null,
                    pest: "przędziorek chmielowiec",
                    dose: "Maksymalna / zalecana dawka dla jednorazowego zastosowania: 1,2 l/ha.",
                    recommended_dose: null,
                    maximum_dose: 44593,
                    unit: "l/ha",
                    deadline: null,
                    group_name: "ROŚLINY SADOWNICZE",
                    small_area: "TAK",
                    application: "profesjonalne",
                    created_at: "2022-09-01T19:03:40.000000Z",
                    updated_at: "2022-09-01T19:03:40.000000Z"
                },
                {
                    id: 6,
                    name: "Abamax 018 EC",
                    permit_number: "R-78/2018",
                    permit_deadline: "2022-04-30",
                    sale_deadline: "2022-10-30",
                    term_for_use: "2022-10-30",
                    type: "Akarycyd, Insektycyd",
                    active_substance: "abamektyna - 18 g",
                    plant: null,
                    pest: "miodówka gruszowa plamista",
                    dose: "Maksymalna / zalecana dawka dla jednorazowego zastosowania: 0,75 l/ha.",
                    recommended_dose: null,
                    maximum_dose: 0.75,
                    unit: "l/ha",
                    deadline: null,
                    group_name: "ROŚLINY SADOWNICZE",
                    small_area: null,
                    application: "profesjonalne",
                    created_at: "2022-09-01T19:03:40.000000Z",
                    updated_at: "2022-09-01T19:03:40.000000Z"
                },
                {
                    id: 7,
                    name: "Abamax 018 EC",
                    permit_number: "R-78/2018",
                    permit_deadline: "2022-04-30",
                    sale_deadline: "2022-10-30",
                    term_for_use: "2022-10-30",
                    type: "Akarycyd, Insektycyd",
                    active_substance: "abamektyna - 18 g",
                    plant: null,
                    pest: "przędziorek chmielowiec",
                    dose: "Maksymalna / zalecana dawka dla jednorazowego zastosowania: 0,05% (50 ml środka w 100 litrach wody).",
                    recommended_dose: null,
                    maximum_dose: null,
                    unit: null,
                    deadline: null,
                    group_name: "ROŚLINY WARZYWNE",
                    small_area: null,
                    application: "profesjonalne",
                    created_at: "2022-09-01T19:03:40.000000Z",
                    updated_at: "2022-09-01T19:03:40.000000Z"
                },
                {
                    id: 8,
                    name: "Abamax 018 EC",
                    permit_number: "R-78/2018",
                    permit_deadline: "2022-04-30",
                    sale_deadline: "2022-10-30",
                    term_for_use: "2022-10-30",
                    type: "Akarycyd, Insektycyd",
                    active_substance: "abamektyna - 18 g",
                    plant: null,
                    pest: "przędziorek chmielowiec",
                    dose: "Maksymalna / zalecana dawka dla jednorazowego zastosowania: 1,2 l/ha.",
                    recommended_dose: null,
                    maximum_dose: 44593,
                    unit: "l/ha",
                    deadline: null,
                    group_name: "ROŚLINY SADOWNICZE",
                    small_area: "TAK",
                    application: "profesjonalne",
                    created_at: "2022-09-01T19:03:40.000000Z",
                    updated_at: "2022-09-01T19:03:40.000000Z"
                },
                {
                    id: 9,
                    name: "Acaramik 018 EC",
                    permit_number: "R-139/2013 zn",
                    permit_deadline: "2022-04-30",
                    sale_deadline: "2022-10-30",
                    term_for_use: "2023-10-30",
                    type: "Akarycyd, Insektycyd",
                    active_substance: "abamektyna - 18 g",
                    plant: null,
                    pest: "przędziorek chmielowiec",
                    dose: "Maksymalna / zalecana dawka dla jednorazowego zastosowania: 1,2 l/ha.",
                    recommended_dose: null,
                    maximum_dose: 44593,
                    unit: "l/ha",
                    deadline: null,
                    group_name: "ROŚLINY SADOWNICZE",
                    small_area: "TAK",
                    application: "profesjonalne",
                    created_at: "2022-09-01T19:03:40.000000Z",
                    updated_at: "2022-09-01T19:03:40.000000Z"
                },
                {
                    id: 10,
                    name: "Acaramik 018 EC",
                    permit_number: "R-139/2013 zn",
                    permit_deadline: "2022-04-30",
                    sale_deadline: "2022-10-30",
                    term_for_use: "2023-10-30",
                    type: "Akarycyd, Insektycyd",
                    active_substance: "abamektyna - 18 g",
                    plant: null,
                    pest: "miodówka gruszowa plamista",
                    dose: "Maksymalna dawka dla jednorazowego zastosowania: 0,75 l/ha_x000D_\nZalecana dawka do jednorazowego stosowania: 0,75 l/ha",
                    recommended_dose: null,
                    maximum_dose: 0.75,
                    unit: "l/ha",
                    deadline: "Środek stosować po okresie kwitnienia drzew i zauważeniu pierwszych objawów uszkodzeń.",
                    group_name: "ROŚLINY SADOWNICZE",
                    small_area: null,
                    application: "profesjonalne",
                    created_at: "2022-09-01T19:03:41.000000Z",
                    updated_at: "2022-09-01T19:03:41.000000Z"
                },
                {
                    id: 11,
                    name: "Acaramik 018 EC",
                    permit_number: "R-139/2013 zn",
                    permit_deadline: "2022-04-30",
                    sale_deadline: "2022-10-30",
                    term_for_use: "2023-10-30",
                    type: "Akarycyd, Insektycyd",
                    active_substance: "abamektyna - 18 g",
                    plant: null,
                    pest: "przędziorek, przędziorek chmielowiec",
                    dose: "Maksymalna dawka dla jednorazowego zastosowania: 0,05% (50 ml środka w 100 litrach wody)_x000D_\nZalecana dawka dla jednorazowego stosowania: 0,05% (50 ml środka w 100 litrach wody)",
                    recommended_dose: null,
                    maximum_dose: null,
                    unit: null,
                    deadline: "Opryskiwać rośliny po zauważeniu szkodnika lub pierwszych objawów uszkodzeń.",
                    group_name: "ROŚLINY WARZYWNE",
                    small_area: null,
                    application: "profesjonalne",
                    created_at: "2022-09-01T19:03:41.000000Z",
                    updated_at: "2022-09-01T19:03:41.000000Z"
                },
                {
                    id: 12,
                    name: "Accent 75 WG",
                    permit_number: "R-151/2013",
                    permit_deadline: "2023-11-06",
                    sale_deadline: "2024-05-06",
                    term_for_use: "2025-05-07",
                    type: "Chwastobójczy",
                    active_substance: "nikosulfuron - 75 %",
                    plant: null,
                    pest: "chwastnica jednostronna, perz właściwy, bodziszek drobny, dymnica pospolita, fiołek polny, gwiazdnica pospolita, jasnota purpurowa, krzywoszyj polny, maruna bezwonna, przytulia czepna, przetacznik perski, psianka czarna, rdest powojowy, rumian polny, szarłat szorstki, tasznik pospolity, tobołki polne, wilczomlecz obrotny, mlecz polny, komosa biała, rdest ptasi",
                    dose: null,
                    recommended_dose: null,
                    maximum_dose: null,
                    unit: null,
                    deadline: null,
                    group_name: "ROŚLINY ROLNICZE",
                    small_area: null,
                    application: "profesjonalne",
                    created_at: "2022-09-01T19:03:41.000000Z",
                    updated_at: "2022-09-01T19:03:41.000000Z"
                },
                {
                    id: 13,
                    name: "Acelan 20 SP",
                    permit_number: "R-35/2019 h.r.",
                    permit_deadline: "2022-04-30",
                    sale_deadline: "2022-10-31",
                    term_for_use: "2023-10-31",
                    type: "Insektycyd",
                    active_substance: "acetamipryd - 20 %",
                    plant: null,
                    pest: "oprzędziki, zmiennik lucernowiec, mszyce, strąkowiec bobowy",
                    dose: "Maksymalna/ zalecana dawka dla jednorazowego zastosowania: 0,2 kg/ha.",
                    recommended_dose: null,
                    maximum_dose: 0.2,
                    unit: "kg/ha",
                    deadline: null,
                    group_name: "ROŚLINY ROLNICZE",
                    small_area: "TAK",
                    application: "amatorskie / profesjonalne",
                    created_at: "2022-09-01T19:03:41.000000Z",
                    updated_at: "2022-09-01T19:03:41.000000Z"
                },
                {
                    id: 14,
                    name: "Acelan 20 SP",
                    permit_number: "R-35/2019 h.r.",
                    permit_deadline: "2022-04-30",
                    sale_deadline: "2022-10-31",
                    term_for_use: "2023-10-31",
                    type: "Insektycyd",
                    active_substance: "acetamipryd - 20 %",
                    plant: null,
                    pest: "zwójka bukóweczka, zwójka siatkóweczka, zwójka różóweczka, zwójki, gąsienice zjadające liście, miodówka gruszowa plamista, miodówka gruszowa czerwona, miodówka gruszowa żółta",
                    dose: null,
                    recommended_dose: null,
                    maximum_dose: null,
                    unit: null,
                    deadline: null,
                    group_name: "ROŚLINY SADOWNICZE",
                    small_area: "TAK",
                    application: "amatorskie / profesjonalne",
                    created_at: "2022-09-01T19:03:41.000000Z",
                    updated_at: "2022-09-01T19:03:41.000000Z"
                },
                {
                    id: 15,
                    name: "Acelan 20 SP",
                    permit_number: "R-35/2019 h.r.",
                    permit_deadline: "2022-04-30",
                    sale_deadline: "2022-10-31",
                    term_for_use: "2023-10-31",
                    type: "Insektycyd",
                    active_substance: "acetamipryd - 20 %",
                    plant: null,
                    pest: "śluzownica ciemna, kwieciak gruszowiec, pryszczarek gruszowiec",
                    dose: "Maksymalna/zalecana dawka dla jednorazowego zastosowania: 0,2 kg/ha._x000D_\nMaksymalna/zalecana dawka dla jednorazowego zastosowania: 2,0 g/100m2.",
                    recommended_dose: null,
                    maximum_dose: 0.2,
                    unit: "kg/ha",
                    deadline: null,
                    group_name: "ROŚLINY SADOWNICZE",
                    small_area: "TAK",
                    application: "amatorskie / profesjonalne",
                    created_at: "2022-09-01T19:03:41.000000Z",
                    updated_at: "2022-09-01T19:03:41.000000Z"
                },
                {
                    id: 16,
                    name: "Acelan 20 SP",
                    permit_number: "R-35/2019 h.r.",
                    permit_deadline: "2022-04-30",
                    sale_deadline: "2022-10-31",
                    term_for_use: "2023-10-31",
                    type: "Insektycyd",
                    active_substance: "acetamipryd - 20 %",
                    plant: null,
                    pest: "zwójka bukóweczka, zwójka siatkóweczka, zwójka różóweczka, zwójka złocienióweczka, gąsienice zjadające liście",
                    dose: null,
                    recommended_dose: null,
                    maximum_dose: null,
                    unit: null,
                    deadline: null,
                    group_name: "ROŚLINY SADOWNICZE",
                    small_area: "TAK",
                    application: "amatorskie / profesjonalne",
                    created_at: "2022-09-01T19:03:41.000000Z",
                    updated_at: "2022-09-01T19:03:41.000000Z"
                },
                {
                    id: 17,
                    name: "Acelan 20 SP",
                    permit_number: "R-35/2019 h.r.",
                    permit_deadline: "2022-04-30",
                    sale_deadline: "2022-10-31",
                    term_for_use: "2023-10-31",
                    type: "Insektycyd",
                    active_substance: "acetamipryd - 20 %",
                    plant: null,
                    pest: "śluzownica ciemna, licinek tarninaczek, kwieciak pestkowiec",
                    dose: "Maksymalna/zalecana dawka dla jednorazowego zastosowania: 0,2 kg/ha._x000D_\nMaksymalna/zalecana dawka dla jednorazowego zastosowania: 2,0 g/100m2.",
                    recommended_dose: null,
                    maximum_dose: 0.2,
                    unit: "kg/ha",
                    deadline: null,
                    group_name: "ROŚLINY SADOWNICZE",
                    small_area: "TAK",
                    application: "amatorskie / profesjonalne",
                    created_at: "2022-09-01T19:03:41.000000Z",
                    updated_at: "2022-09-01T19:03:41.000000Z"
                },
                {
                    id: 18,
                    name: "Acelan 20 SP",
                    permit_number: "R-35/2019 h.r.",
                    permit_deadline: "2022-04-30",
                    sale_deadline: "2022-10-31",
                    term_for_use: "2023-10-31",
                    type: "Insektycyd",
                    active_substance: "acetamipryd - 20 %",
                    plant: null,
                    pest: "mszyce, zwójka siatkóweczka, zwójka różóweczka, zwójki, gąsienice zjadające liście",
                    dose: null,
                    recommended_dose: null,
                    maximum_dose: null,
                    unit: null,
                    deadline: null,
                    group_name: "ROŚLINY SADOWNICZE",
                    small_area: "TAK",
                    application: "amatorskie / profesjonalne",
                    created_at: "2022-09-01T19:03:41.000000Z",
                    updated_at: "2022-09-01T19:03:41.000000Z"
                },
                {
                    id: 19,
                    name: "Acelan 20 SP",
                    permit_number: "R-35/2019 h.r.",
                    permit_deadline: "2022-04-30",
                    sale_deadline: "2022-10-31",
                    term_for_use: "2023-10-31",
                    type: "Insektycyd",
                    active_substance: "acetamipryd - 20 %",
                    plant: null,
                    pest: "krzywik, pryszczarek porzeczkowiec, owocnica, przeziernik porzeckowiec",
                    dose: "Maksymalna/zalecana dawka dla jednorazowego zastosowania: 0,2 kg/ha._x000D_\nMaksymalna/zalecana dawka dla jednorazowego zastosowania: 2,0 g/100m2.",
                    recommended_dose: null,
                    maximum_dose: 0.2,
                    unit: "kg/ha",
                    deadline: null,
                    group_name: "ROŚLINY SADOWNICZE",
                    small_area: "TAK",
                    application: "amatorskie / profesjonalne",
                    created_at: "2022-09-01T19:03:41.000000Z",
                    updated_at: "2022-09-01T19:03:41.000000Z"
                },
                {
                    id: 20,
                    name: "Acelan 20 SP",
                    permit_number: "R-35/2019 h.r.",
                    permit_deadline: "2022-04-30",
                    sale_deadline: "2022-10-31",
                    term_for_use: "2023-10-31",
                    type: "Insektycyd",
                    active_substance: "acetamipryd - 20 %",
                    plant: null,
                    pest: "kwieciak malinowiec",
                    dose: "Maksymalna/zalecana dawka dla jednorazowego zastosowania: 0,2 kg/ha._x000D_\nMaksymalna/zalecana dawka dla jednorazowego zastosowania: 2,0 g/100m2.",
                    recommended_dose: null,
                    maximum_dose: 0.2,
                    unit: "kg/ha",
                    deadline: null,
                    group_name: "ROŚLINY SADOWNICZE",
                    small_area: "TAK",
                    application: "amatorskie / profesjonalne",
                    created_at: "2022-09-01T19:03:41.000000Z",
                    updated_at: "2022-09-01T19:03:41.000000Z"
                },
            ]
        }
    },
    mutations,
    actions,
    getters
}